{% set name = "crepes" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ebe607f5f45de4e40f17779fc3670cde5b3f3fb87f65b4dc35ecd54911b4c50

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - crepes

about:
  home: https://github.com/henrikbostrom/crepes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conformal regressors and predictive systems (crepes)
  doc_url: https://crepes.readthedocs.io/en/latest/
  dev_url: https://github.com/henrikbostrom/crepes

extra:
  recipe-maintainers:
    - henrikbostrom
