{% set name = "crepes" %}
{% set version = "0.8.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crepes-{{ version }}.tar.gz
  sha256: ce11cc2befe824db146b06e0de0b1d491cf74fe86832815e9a63bc2bec324410

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: {{ build }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - scikit-learn

test:
  imports:
    - crepes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/henrikbostrom/crepes
  dev_url: https://github.com/henrikbostrom/crepes
  doc_url: https://crepes.readthedocs.io/en/latest/
  summary: Conformal classifiers, regressors, and predictive systems (crepes)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - henrikbostrom
    
