{% set name = "crepes" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: adc06ba70c891b77c0eab6722f224d18681e816de5e11157ea9b512a4f088dce

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - crepes

about:
  home: https://github.com/henrikbostrom/crepes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conformal classifiers, regressors and predictive systems (crepes)
  doc_url: https://crepes.readthedocs.io/en/latest/
  dev_url: https://github.com/henrikbostrom/crepes

extra:
  recipe-maintainers:
    - henrikbostrom
